site_name: Shenanigan Wiki
site_url: https://she.energy/join
site_author: 'Shenanigan Core Team'
site_description: 'Learn about Shenanigan'
repo_name: '/wiki'
repo_url: https://github.com/ShenaniganDApp/wiki/
edit_uri: edit/master/docs/
docs_dir: docs
nav:
    - Home: index.md
    - About: about.md
    - Collaborate: collaboration.md
theme:
    name: material
    custom_dir: 'material'
    palette:
      primary: 'pink'
      accent: 'pink'
    language: 'en'

extra:
    palette:
      primary: 'pink'
      accent: 'amber'
    # social:
    # - type: 'comment-o'
    #   link: 'http://she.energy/join/'
    # - type: 'twitter'
    #   link: 'https://twitter.com/She_Dapp'
    # - type: 'github'
    #   link: 'https://github.com/ShenaniganDApp'
    # - type: 'facebook'
    #   link: 'https://www.facebook.com/shenanigan.dapp/'
    # - type: 'youtube'
    #   link: 'https://www.youtube.com/channel/UCyENEycuNXfntLJLSeIuWX'
